# This is a basic workflow to help you get started with Actions

name: CI
on: [push, pull_request]

jobs:
  
  linter:
    name: PHP Lint
    runs-on: ubuntu-latest
    steps:
      - name: PHP Lint
        uses: michaelw90/PHP-Lint@2.1.0
    
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: PHPStan
      uses: docker://oskarstark/phpstan-ga
      with:
        args: analyse src/

  phpinsights:
    name: PHP-Insights
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: PHP-Insights
      uses: docker://tienvx/phpinsights-action
