name: CI
on: pull_request

jobs:
 
  php_linter:
    name: PHP Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: overtrue/phplint@master
        with:
          path: .
    
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: PHPStan
      uses: docker://oskarstark/phpstan-ga
      with:
        args: analyse ./*.php* ./inc/*.php
