name: CI
on: pull_request

jobs:
 
  php_linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: overtrue/phplint@master
        with:
          path: ./
          args: --no-configuration
   
  php_cs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PHP Code Style (phpcs)
        uses: chekalsky/phpcs-action@v1
        with:
          args: --standard=PHPCompatibility --encoding=utf-8 --extensions=php,dist "$GITHUB_WORKSPACE"

  php_stan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: PHP Stan
      uses: docker://oskarstark/phpstan-ga
      with:
        args: analyse ./*.php* ./inc/*.php
