name: CI
on: [push, pull_request]

jobs:
 
  php_linter:
    name: PHP Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: overtrue/phplint@master
        with:
          path: .
          args: --no-configuration
    
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: PHPStan
      uses: docker://oskarstark/phpstan-ga
      with:
        args: analyse ./*.php ./inc/*.php

  phpinsights:
    name: PHP-Insights
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: PHP-Insights
      uses: docker://tienvx/phpinsights-action
      with:
        args: analyse .
